### ISSUE TITLE
prometheus has some wrong

### ISSUE THREAD

**Issue by wnark** [tamersunion/tracker#1]
https://github.com/chihaya/chihaya/blob/master/dist/prometheus/prometheus.yaml
If you use your configuration, prometheus will not be able to connect to the service
Prometheus can work normally after changing the internal port of chihaya configuration to 6880

**Comment by HanadaLee** [comment]
chihaya had updated config format. you should use new config format in new version. I will compile a new chihaya version and update this guide soon.
